platform :ios, '6.0'
target "BallSirForiOS" do
    pod 'AFNetworking','~>2.3.1'
    pod 'SSToolkit','~>2.0.0'
    pod 'ConciseKit','~>0.1.2'
    pod 'MagicalRecord','~>2.2'
    pod 'SFHFKeychainUtils','~>0.0.1'
    pod 'SBJson','~>4.0.1'
    pod 'SDURLCache','~>1.3'
    pod 'SSKeychain','~>1.2.2'
    pod 'Reachability','~>3.1.1'
    pod 'JSBadgeView','~>1.3.2'
end

